language: python
python:
  - 3.6
install:
  - cp contrib/sample-env .env
  - pip install -q -r requirements-dev.txt codecov
script:
  - flake8 .
  - pytest --cov-branch --cov=lojinha
after_success:
  - codecov